AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sends out tweets every day :-).

Globals:
    Function:
        Timeout: 300
        AutoPublishAlias: live
        DeploymentPreference:
            Type: AllAtOnce

Resources:

    SimpleTwitterApp:
        Type: AWS::Serverless::Function
        Condition: False
        Properties:
            FunctionName: twitter-bot
            CodeUri: dist/
            Handler: text.handler
            Runtime: python3.8
            Policies:
              - Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action: ssm:GetParameter
                    Resource: '*'
            Events:
              TweetEveryDay:
                Type: Schedule
                Properties:
                  Schedule: rate(1 year)
